execute pathogen#infect()

" Color schemes
set t_Co=256
let g:rehash256=1
colorscheme molokai

" File settings
filetype plugin indent on
set fileformats=unix,dos,mac

" Syntax hightlighting
syntax on
map <silent> <C-h> :nohlsearch<CR>

" Line numbering
" set relativenumber
set number

" Cursor movement
set mouse=nicr
nnoremap j gj
nnoremap k gk
nnoremap 0 g^
nnoremap $ g$
map J jzz
map K kzz
map L zz

" Disable line breaks unless the <Enter> key is hit
set wrap
set linebreak
set nolist
set textwidth=0
set wrapmargin=0

" Normal backspace behavior (non-Vi)
set backspace=2

" Tab settings
set smarttab
set tabstop=2
set shiftwidth=2
set expandtab

" Searching
set incsearch
set hlsearch
set ignorecase
set smartcase
set magic

" Reload vimrc
nmap <silent> <leader>r :so ~/.vimrc<cr>

" Vim comments
nmap ge gac
vmap ge ga

" Copy/Paste to/from X buffer
vnoremap gy "+y
vnoremap gd "+d
vnoremap gc "+c
nnoremap gC "+C
nnoremap gcc "+cc
nnoremap gD "+D
nnoremap gd "+d
nnoremap gy "+y
nnoremap <C-y> :%y+"<cr>
nnoremap gp "+p
vnoremap gp "+p

" Bracket highlighting
set showmatch
set matchtime=2

" Disable file backups + swapfile creation
set noswapfile
set nobackup
set nowb

" Command mode settings
set wildmenu
set wildmode=longest:list,full
set shellslash
set history=100

" Vim notes
let g:notes_directories=['~/notes']

" Emmet
let g:user_emmet_leader_key='<C-f>'

" GUI options
if has('gui_running')
  set guifont=Bitstream\ Vera\ Sans\ Mono\ 9
  autocmd GUIEnter * set vb t_vb=
  autocmd VimEnter * set vb t_vb=
  set guioptions-=T
  set guioptions-=e
  set guioptions-=r
  set guioptions-=m
endif

set pumheight=20
set completeopt=menuone

" Neocomplete / completion menu
" inoremap <expr><TAB> pumvisible() ? "\<C-n>" : "\<TAB>"
" inoremap <expr><S-TAB> pumvisible() ? "\<C-p>" : "\<S-TAB>"
" nnoremap <C-n> :NeoCompleteToggle<CR>
" let g:neocomplete#enable_at_startup=1
" let g:neocomplete#enable_ignore_case=0
" let g:neocomplete#enable_camel_case=0
" let g:neocomplete#enable_refresh_always=1
" let g:neocomplete#enable_prefetch=1
" if !exists('g:neocomplete#sources#omni#input_patterns')
"   let g:neocomplete#sources#omni#input_patterns = {}
" endif
" if !exists('g:neocomplete#force_omni_input_patterns')
"   let g:neocomplete#force_omni_input_patterns = {}
" endif

" Syntastic
let g:syntastic_javascript_jshint_args = '--config /home/jake/source/chromium-vim/.jshintrc'
nnoremap <C-s> :SyntasticToggleMode<CR>
hi SpellCap term=reverse ctermbg=160
let g:neocomplete#auto_completion_start_length=2
let g:neocomplete#force_overwrite_completefunc=1
let g:neocomplete#max_keyword_width=80
let g:neocomplete#sources#tags#cache_limit_size=5000000

" Airline
set laststatus=2
let g:airline_theme='molokai'
let g:airline_left_sep=''
let g:airline_right_sep=''
" let g:airline_left_sep=''
" let g:airline_right_sep=''
let g:tcommentMapLeaderOp1="ga"
map <C-t> :tabnew<CR>:Explore<CR>
map <A-q> :q<CR>
map <C-S-q> :q!<CR>

" Miscellaneous
vnoremap . :normal .<CR>
set visualbell t_vb=
set ttimeoutlen=0
set ttyfast
set timeoutlen=500
set lazyredraw
vnoremap <C-e> <C-u>
nnoremap <C-e> <C-u>
let g:run_fifo = "/tmp/vim-run_fifo"
let g:run_exec_on_write = 1

" Mappings
nnoremap Q @q
nnoremap @@ @q
vmap gq ygvge
nmap gqq yyge
set nofoldenable
nnoremap ' `
nnoremap ` '
nnoremap '' ``zz
nnoremap `` ``zz
vnoremap < <gv
vnoremap > >gv
let loaded_matchparen = 1
nnoremap <C-p> :SyntasticToggleMode<CR>
nnoremap go mto<Esc>`t
nnoremap gO mtO<Esc>`t
inoremap <C-j> <Space><Esc>T)C {<CR>}<Esc>O
nnoremap <C-j> :source $MYVIMRC<CR>
vnoremap ab :normal Va{o^<CR>
vmap ib :normal Va{o0<CR>
omap <silent> ab :normal Vab<CR>
omap <silent> ib i{<CR>
set cursorline
hi CursorLine ctermbg=235 ctermfg=none cterm=none
" hi CursorLine ctermbg=none ctermfg=none
hi CursorLineNr ctermfg=239 ctermbg=234
hi Search ctermbg=252 ctermfg=232

au BufRead,BufNewFile *.md set filetype=markdown
autocmd FileType javascript setlocal omnifunc=js#CompleteJS
map <C-j> :source ~/.vimrc<CR>
let g:jschromeapis = 1
let g:javascript#bracehi = 1
" let g:javascript#equalhi = 1
