#! /bin/sh

# bspc monitor -d 1 2 3 4 5 6
bspc monitor -d 001 010 011 100 101 110 111

bspc config border_width 0
# bspc config window_gap 12
# bspc config top_padding 16
bspc config window_gap 0
bspc config top_padding 15
bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true

compton &
urxvtd -q &
xsetroot -cursor_name left_ptr &
xrdb ~/.Xresources &
xmodmap /home/jake/.macros &
nitrogen --restore &
xset r rate 300 40 &
xset m 3/2.5 &
~/.config/bspwm/panel/init.sh &
