#!/bin/sh

bspc config border_width 0
bspc config window_gap 15

bspc monitor -d 0 1 2 3 4 5

bspc config top_padding 18
bspc config -m eDP1 window_gap 10
bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config click_to_focus true
bspc config pointer_modifier mod1

wmname LG3D

# bspc rule -a \* floating=on

compton &
~/.config/bspwm/panel/init.sh &
