#!/bin/sh

bspc monitor -d 0 1 2 3 4 5

# bspc rule -a \* floating=on
bspc config -m eDP1 border_width 0
# bspc config -m eDP1 window_gap 0
bspc config top_padding 18
bspc config -m eDP1 window_gap 15
bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true

compton &

~/.config/bspwm/panel/init.sh &
