#! /bin/sh

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width        0
#bspc config window_gap          12
#bspc config top_padding         16
bspc config window_gap 26
bspc config top_padding 16
bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     true

compton &
urxvtd -q &
xsetroot -cursor_name left_ptr &
xrdb ~/.Xresources &
xmodmap /home/jake/.macros &
nitrogen --restore &
xset r rate 400 35 &
xset m 1/2 &
dzconky &
