#!/bin/bash

case $1 in
  i)
    sudo cpupower frequency-info
    ;;
  h)
    sudo cpupower frequency-set -d 3.4GHz -u 3.4GHz -g performance
    ;;
  n)
    sudo cpupower frequency-set -d 800MHz -u 3.4GHz -g powersave
    ;;
  l)
    sudo cpupower frequency-set -d 800MHz -u 800MHz -g powersave
    ;;
  *)
    echo -e "Usage:\ni ==> info\nh ==> high power (3.4GHz)\nn ==> normal power (800MHz-3.4GHz)\nl ==> low power (800MHz)"
    ;;
esac
