#!/bin/sh

BG="#1B1D1E"
FG="#8F8F8F"
FONT='Terminus:pixelsize=11:style=Bold'
killall dzen2 conky > /dev/null
#conky | dzen2 -h '18' -fn "$FONT" -bg $BG -fg $FG -p -e & sleep 0.05; transset-df --no-regex -n 'dzen title' .85
conky | dzen2 -h '18' -fn "$FONT" -bg $BG -fg $FG -p -e &
