#!/usr/bin/env zsh

CLASS_PATH='.:/usr/share/java/junit.jar:/usr/share/java/hamcrest-core.jar'
TMP=`mktemp -d`

javac -cp $CLASS_PATH -d $TMP "${@:1}"

MAIN=`grep -lE 'import\s+org\s*\.\s*junit' ${@:1} | head -1 | sed 's/\..*//'`

if [[ $MAIN != '' ]]; then
  cd $TMP
  java -cp $CLASS_PATH org.junit.runner.JUnitCore $MAIN
else
  MAIN=`echo $1 | sed 's/\..*//'`
  cd $TMP
  java -cp $CLASS_PATH $MAIN
fi

rm -r $TMP
