#!/bin/sh

DEV=`iw dev | sed -n 2p | grep -oE '\S+$'`
PROFILES=(`ls /etc/netctl | grep $DEV`)

for ((i = 0; i < ${#PROFILES[@]}; i++)); do
  echo -e "\e[92m[$i]\e[0m" ${PROFILES[$i]}
done

read -p "Choose a network profile: " choice
[[ $choice =~ '[^0-9]' || $choice -ge $i ]] && exit

sudo netctl stop-all
sudo ip link set $DEV down
sudo netctl start ${PROFILES[$choice]}
