#!/bin/sh

wldev=`iw dev | grep "Interface" | head -n 1 | egrep -o "\S+$"`
profiles=`ls /etc/netctl | grep $wldev`;
c=1; echo

for i in $profiles; do
	echo -e "\e[92m[$c]\e[0m" $i
	profile_arr[c]=$i
	c=`expr $c + 1`
done

read -p "Choose a network profile: " choice
if [[ `echo $choice | grep -E "^[0-9]{,}$"` -eq "" ]]; then
	exit
fi

if [[ $choice -lt c ]]; then
	sudo ip link set $wldev down
	sudo netctl stop-all
	sudo netctl start ${profile_arr[$choice]}
fi
